bind_host: 0.0.0.0
bind_port: 3000
beta_bind_port: 0
users: []
auth_attempts: 5
block_auth_min: 15
http_proxy: ""
language: ""
debug_pprof: false
web_session_ttl: 720
dns:
  bind_hosts:
  - 0.0.0.0
  port: 3053
  statistics_interval: 1
  querylog_enabled: true
  querylog_file_enabled: false
  querylog_interval: 6h
  querylog_size_memory: 1000
  anonymize_client_ip: false
  protection_enabled: true
  blocking_mode: default
  blocking_ipv4: ""
  blocking_ipv6: ""
  blocked_response_ttl: 10
  parental_block_host: family-block.dns.adguard.com
  safebrowsing_block_host: standard-block.dns.adguard.com
  ratelimit: 20
  ratelimit_whitelist: []
  refuse_any: true
  upstream_dns:
  - 94.140.14.14
  - 1.1.1.1
  - 9.9.9.9
  upstream_dns_file: ""
  bootstrap_dns:
  - 94.140.14.14
  - 94.140.15.15
  - 2a10:50c0::ad1:ff
  - 2a10:50c0::ad2:ff
  - 1.1.1.1
  - 1.0.0.1
  - 2606:4700:4700::1111
  - 2606:4700:4700::1001
  - 9.9.9.10
  - 149.112.112.10
  - 2620:fe::10
  - 2620:fe::fe:10
  all_servers: false
  fastest_addr: false
  fastest_timeout: 1s
  allowed_clients: []
  disallowed_clients: []
  blocked_hosts:
  - version.bind
  - id.server
  - hostname.bind
  trusted_proxies:
  - 127.0.0.0/8
  - ::1/128
  cache_size: 4194304
  cache_ttl_min: 0
  cache_ttl_max: 0
  cache_optimistic: false
  bogus_nxdomain: []
  aaaa_disabled: false
  enable_dnssec: false
  edns_client_subnet: false
  max_goroutines: 300
  ipset: []
  filtering_enabled: true
  filters_update_interval: 72
  parental_enabled: false
  safesearch_enabled: false
  safebrowsing_enabled: true
  safebrowsing_cache_size: 1048576
  safesearch_cache_size: 1048576
  parental_cache_size: 1048576
  cache_time: 30
  rewrites: []
  blocked_services: []
  upstream_timeout: 10s
  private_networks: []
  use_private_ptr_resolvers: true
  local_ptr_upstreams: []
tls:
  enabled: false
  server_name: ""
  force_https: false
  port_https: 443
  port_dns_over_tls: 853
  port_dns_over_quic: 784
  port_dnscrypt: 0
  dnscrypt_config_file: ""
  allow_unencrypted_doh: false
  strict_sni_check: false
  certificate_chain: ""
  private_key: ""
  certificate_path: ""
  private_key_path: ""
filters:
- enabled: true
  url: https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt
  name: AdGuard DNS filter
  id: 1
- enabled: true
  url: https://adaway.org/hosts.txt
  name: AdAway Default Blocklist
  id: 2
- enabled: true
  url: https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/filters.txt
  name: uBlockOrigin
  id: 1678068030
- enabled: true
  url: https://raw.githubusercontent.com/durablenapkin/scamblocklist/master/hosts.txt
  name: Scam Blocklist by DurableNapkin Hosts
  id: 1678071896
- enabled: true
  url: https://raw.githubusercontent.com/mitchellkrogza/The-Big-List-of-Hacked-Malware-Web-Sites/master/hosts
  name: The Big List of Hacked Malwaware Hosts
  id: 1678071897
- enabled: true
  url: https://malware-filter.gitlab.io/malware-filter/urlhaus-filter-agh.txt
  name: Malicious URL Blocklist AGH
  id: 1678071898
- enabled: true
  url: https://anti-ad.net/easylist.txt
  name: Privacy-protection-tools/anti-ad AGH
  id: 1678071899
- enabled: true
  url: https://pgl.yoyo.org/adservers/serverlist.php?hostformat=adblockplus&showintro=1&mimetype=plaintext
  name: Peter Lowe's List Hosts
  id: 1678071900
- enabled: true
  url: https://raw.githubusercontent.com/DandelionSprout/adfilt/master/GameConsoleAdblockList.txt
  name: Game Console Adblock AGH&Pi-hole
  id: 1678071901
- enabled: true
  url: https://someonewhocares.org/hosts/zero/hosts
  name: Dan Pollock's List Hosts
  id: 1678071902
- enabled: true
  url: https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareAdGuardHome.txt
  name: Dandelion Sprout's Anti-Malware DNS
  id: 1678071903
- enabled: true
  url: https://raw.githubusercontent.com/blocklistproject/Lists/master/malware.txt
  name: The Block List Project - Malwaware Hosts
  id: 1678071904
- enabled: true
  url: https://raw.githubusercontent.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/master/_generator_lists/bad-referrers.list
  name: Nginx Ultimate Bad Bot Blocker Domains
  id: 1678071905
- enabled: true
  url: https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Extension/GoodbyeAds-YouTube-AdBlock.txt
  name: GoodbyeAds YouTube Hosts
  id: 1678071906
- enabled: true
  url: https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Extension/GoodbyeAds-Xiaomi-Extension.txt
  name: GoodbyeAds Xiaomi Hosts
  id: 1678097940
- enabled: true
  url: https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Extension/GoodbyeAds-Samsung-AdBlock.txt
  name: GoodbyeAds Samsung Hosts
  id: 1678097941
- enabled: true
  url: https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt
  name: Blacklist Adserver Hosts
  id: 1678097942
- enabled: true
  url: https://www.github.developerdan.com/hosts/lists/ads-and-tracking-extended.txt
  name: Lightswitch05's Hosts ads-and-tracking extended
  id: 1678097943
- enabled: true
  url: https://www.github.developerdan.com/hosts/lists/amp-hosts-extended.txt
  name: Lightswitch05's Hosts amp-hosts-extended
  id: 1678097944
- enabled: true
  url: https://www.github.developerdan.com/hosts/lists/dating-services-extended.txt
  name: Lightswitch05's Hosts dating-service
  id: 1678097945
- enabled: true
  url: https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/hosts.txt
  name: NoCoin Filter Hosts
  id: 1678097946
- enabled: true
  url: https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/firehol_level1.netset
  name: Firehol_level1 max protection IP Lists
  id: 1678097947
- enabled: true
  url: https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/firehol_level4.netset
  name: Firehol_level4 max protection IP Lists
  id: 1678097948
- enabled: true
  url: https://www.team-cymru.org/Services/Bogons/fullbogons-ipv6.txt
  name: Team Cymru Fullbogons (IPv6) IP Lists
  id: 1678097949
- enabled: true
  url: https://www.team-cymru.org/Services/Bogons/fullbogons-ipv4.txt
  name: Team Cymru Fullbogons (IPv4) IP Lists
  id: 1678097950
- enabled: true
  url: https://raw.githubusercontent.com/bigdargon/hostsVN/master/option/hosts-iOS
  name: hostsVN IOS Ads Hosts
  id: 1678097951
- enabled: true
  url: https://raw.githubusercontent.com/olbat/ut1-blacklists/master/blacklists/phishing/urls
  name: Phishing & Malware OLBAT Domains
  id: 1678097952
- enabled: true
  url: https://raw.githubusercontent.com/UnluckyLuke/BlockUnderRadarJunk/master/blockunderradarjunk-list.txt
  name: BlockUnderRadarJunk Domains
  id: 1678097953
- enabled: true
  url: https://hblock.molinero.dev/hosts_adblock.txt
  name: Phishing Army | hBlock Hosts
  id: 1678097954
- enabled: true
  url: https://raw.githubusercontent.com/eEIi0A5L/adblock_filter/master/mochi_filter.txt
  name: ADS Mochi DNS Filter Abroad
  id: 1678097955
- enabled: true
  url: https://raw.githubusercontent.com/kowith337/PersonalFilterListCollection/master/hosts/hosts_google_adservice_id.txt
  name: Google Ads and ID.G tracking Hosts
  id: 1678097956
- enabled: true
  url: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
  name: Unified hosts = (adware + malware)
  id: 1678097957
- enabled: true
  url: https://v.firebog.net/hosts/Prigent-Malware.txt
  name: Prigent-Malware Domains
  id: 1678097958
- enabled: true
  url: https://v.firebog.net/hosts/static/w3kbl.txt
  name: SUS Lists Personal by WaLLy3K Domains
  id: 1678097959
- enabled: true
  url: https://raw.githubusercontent.com/matomo-org/referrer-spam-blacklist/master/spammers.txt
  name: Spam blacklist Domains
  id: 1678097960
- enabled: true
  url: https://raw.githubusercontent.com/VeleSila/yhosts/master/hosts
  name: Spam Suspicious by ValeSila Hosts
  id: 1678097961
- enabled: true
  url: https://v.firebog.net/hosts/Easyprivacy.txt
  name: Easyprivacy Firebog Domains
  id: 1678097962
- enabled: true
  url: https://hostfiles.frogeye.fr/multiparty-trackers-hosts.txt
  name: Privacy multiparty-trackers Hosts
  id: 1678097963
- enabled: true
  url: https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/android-tracking.txt
  name: Privacy android-tracking Domains
  id: 1678097964
- enabled: true
  url: https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/SmartTV-AGH.txt
  name: Smart-TV Blocklist for AGH
  id: 1678097965
- enabled: true
  url: https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-blocklist.txt
  name: NoTrack Tracker Domains
  id: 1678097966
- enabled: true
  url: https://osint.digitalside.it/Threat-Intel/lists/latestdomains.txt
  name: OSINT.digitalside.it Malicious Domains
  id: 1678097967
- enabled: true
  url: https://raw.githubusercontent.com/mitchellkrogza/Phishing.Database/master/active-domains.adblock
  name: Phishing Domains Blocklist by mitchellkrogza
  id: 1678097968
- enabled: true
  url: https://raw.githubusercontent.com/jdlingyu/ad-wars/master/hosts
  name: Ad-wars Hosts
  id: 1678097969
- enabled: true
  url: https://raw.githubusercontent.com/brave/adblock-lists/master/brave-unbreak.txt
  name: Brave DNS
  id: 1678097970
- enabled: true
  url: https://raw.githubusercontent.com/PolishFiltersTeam/KADhosts/master/KADhosts.txt
  name: KADhosts
  id: 1678097971
- enabled: true
  url: https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/filters-2020.txt
  name: uBlockOrigin2020
  id: 1678097972
- enabled: true
  url: https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/filters-2021.txt
  name: uBlockOrigin2021
  id: 1678097973
- enabled: true
  url: https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/filters-2022.txt
  name: uBlockOrigin2022
  id: 1678097974
- enabled: true
  url: https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/filters-2023.txt
  name: uBlockOrigin2023
  id: 1678097975
- enabled: true
  url: https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/annoyances.txt
  name: uBlockOrigin – Annoyances
  id: 1678097976
- enabled: true
  url: https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/privacy.txt
  name: uBlockOrigin – Privacy
  id: 1678097977
- enabled: true
  url: https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/badware.txt
  name: uBlock Origin – Badware
  id: 1678097978
- enabled: true
  url: https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/quick-fixes.txt
  name: uBlockOrigin - Quick fixes list
  id: 1678097979
- enabled: true
  url: https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/resource-abuse.txt
  name: uBlockOrigin – Resource abuse
  id: 1678097980
- enabled: true
  url: https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/unbreak.txt
  name: uBlockOrigin – Unbreak
  id: 1678097981
- enabled: true
  url: https://raw.githubusercontent.com/TogoFire-Home/AD-Settings/main/Filters/filter.txt
  name: Personal List
  id: 1678097984
- enabled: true
  url: https://securereload.tech/Phishing/Lists/Latest/
  name: SecureReload Phishing Domains
  id: 1678097985
whitelist_filters:
- enabled: true
  url: https://raw.githubusercontent.com/TogoFire-Home/AD-Settings/main/Filters/whitelist.txt
  name: AGH Whitelist
  id: 1678071894
- enabled: true
  url: https://raw.githubusercontent.com/hl2guide/AdGuard-Home-Whitelist/main/whitelist.txt
  name: Hl2 agh whitelist
  id: 1678071895
- enabled: true
  url: https://raw.githubusercontent.com/im-sm/Pi-hole-Torrent-Blocklist/main/all-torrent-trackres.txt
  name: Torrent Whitelist
  id: 1678097988
- enabled: true
  url: https://raw.githubusercontent.com/AdguardTeam/HttpsExclusions/master/exclusions/banks.txt
  name: Banks Whitelist
  id: 1678097989
user_rules: []
dhcp:
  enabled: false
  interface_name: ""
  local_domain_name: lan
  dhcpv4:
    gateway_ip: ""
    subnet_mask: ""
    range_start: ""
    range_end: ""
    lease_duration: 86400
    icmp_timeout_msec: 1000
    options: []
  dhcpv6:
    range_start: ""
    lease_duration: 86400
    ra_slaac_only: false
    ra_allow_slaac: false
clients:
  runtime_sources:
    whois: true
    arp: true
    rdns: true
    dhcp: true
    hosts: true
  persistent: []
log_compress: false
log_localtime: false
log_max_backups: 0
log_max_size: 100
log_max_age: 3
log_file: ""
verbose: false
os:
  group: ""
  user: ""
  rlimit_nofile: 0
schema_version: 14
